runtime: python310

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

env_variables:
  # OpenAI API
  OPENAI_API_KEY: "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"
  # Google OAuth
  GOOGLE_CLIENT_ID: "1026540012637-f0nq4fcftaveo2aidj3htfef5td7bm4d.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  # Google SQL
  DB_USER: "cicero-user"
  DB_PASS: "thesebootsaremadeforcoding"
  #INSTANCE_HOST: "34.89.61.194"
  DB_NAME: "cicero-db"
  DB_PORT: "1433"
  #PROJECT_ID: "cicero-cs50-final-project"
  INSTANCE_CONNECTION_NAME: "cicero-cs50-final-project:europe-west2:cicero-sql"
  #INSTANCE_UNIX_SOCKET: "/cloudsql/cicero-cs50-final-project:europe-west2:cicero-sql"